config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'
  resources :categories
  resources :recipes do
    collection do
      get :import
      post :confirm
    end
  end
  root 'static_pages#home'
  resources :users
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to  :user
  has_many    :categories, through: :recipe_category_relations
  has_many    :recipe_category_relations, dependent: :destroy
  has_many    :ingredients,  dependent: :destroy
  has_many    :steps,        dependent: :destroy
  has_one_attached :image

  accepts_nested_attributes_for :ingredients, allow_destroy: true
  accepts_nested_attributes_for :steps,       allow_destroy: true
  
  validates :user_id,     presence: true
  validates :name,        presence: true
  validates :description, length: { maximum: 140 }
  validates :url,   format: /\A#{URI::regexp(%w(http https))}\z/, allow_blank: true
  validates :cooktime,      numericality: { only_integer: true }, allow_blank: true

  def grab_image(url)
    require 'open-uri'
    downloaded_image = open(url)
    self.image.attach(io: downloaded_image  , filename: "foo.jpg")
  end

  def minTosec
    if self.last == "S"
      self.gsub!("PT", "").gsub!("S", "").to_i / 60
    else
      self.gsub!("PT", "").gsub!("M", "").to_i
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :check_url, only: [:confirm]
  before_action :redirect_login

  def show
    @recipe = Recipe.find(params[:id])
  end

  def index
    @recipes = current_user.recipes.all
  end

  def new
    @recipe = Recipe.new
    @recipe.ingredients.build
    @recipe.steps.build
  end

  def import   
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)

    if @recipe.save
      flash[:success] = "レシピを作成しました"
      redirect_to @recipe
    else
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:recipe][:id])

    if @recipe.update(recipe_params)
      flash[:success] = "レシピを更新しました"
      redirect_to @recipe
    else
      render :edit
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_url
    flash[:success] = "レシピを削除しました"
  end

  def confirm
    agent = Mechanize.new
    page = agent.get(params[:url])

    # application/ld+jsonでレシピ定義されている部分を取得
    if params[:url].include?("delishkitchen")
      js = page.search('script[type="application/ld+json"]')[1].text
    else
      js = page.at('script[type="application/ld+json"]').text
    end

    # JSON形式に変換して各パーツを取得
    elements = JSON[js]
    recipe = current_user.recipes.build

    #以下、レシピの各パーツを取得
    recipe.name = elements["name"]
    recipe.description = elements["description"]

    # URL取得
    if elements["mainEntityOfPage"].instance_of?(String)
      recipe.url = elements["mainEntityOfPage"]
    else
      recipe.url = elements["mainEntityOfPage"]["@id"]
    end

    # 何人分のレシピか取得
    if elements["recipeYield"].include?("servings")
      recipe.recipeYield = elements["recipeYield"].gsub!("servings","人分")
    else
      recipe.recipeYield = elements["recipeYield"]
    end

    # 調理時間取得（リファクタリングできそう、あとで取り組みたい）    
    if elements["totalTime"].present?
      if elements["totalTime"].last == "S"
        recipe.cooktime = elements["totalTime"].gsub!("PT", "").gsub!("S", "").to_i / 60
      elsif elements["cookTime"].last == "M"
        recipe.cooktime = elements["totalTime"].gsub!("PT", "").gsub!("M", "").to_i
      else
        recipe.cooktime = ""
      end
    elsif elements["cookTime"].present?
      if elements["cookTime"].last == "S"
        recipe.cooktime = elements["cookTime"].gsub!("PT", "").gsub!("S", "").to_i / 60
      elsif elements["cookTime"].last == "M"
        recipe.cooktime = elements["cookTime"].gsub!("PT", "").gsub!("M", "").to_i
      else
        recipe.cooktime = ""
      end
    else
      recipe.cooktime = ""
    end

    # イメージ画像取得
    if elements["image"].instance_of?(Array)
      recipe.grab_image(elements["image"].first)
    elsif elements["image"].instance_of?(Hash)
      recipe.grab_image(elements["image"]["url"])
    else
      recipe.grab_image(elements["image"])
    end
    
    # レシピ保存
    recipe.save

    # 材料とその分量取得
    elements["recipeIngredient"].each do |ingredient|
      ingredient = recipe.ingredients.build(
        name: ingredient.split(" ")[0],
        quantity_amount: ingredient.split(" ")[1])
      ingredient.save
    end

    # 作り方取得
    if elements["recipeInstructions"].instance_of?(String)
      how_to_steps = elements["recipeInstructions"].split("作り方")
      how_to_steps.each do |instruction|
        step = recipe.steps.build(body: instruction) 
        step.save
      end
    else
      elements["recipeInstructions"].each do |step|
        step = recipe.steps.build(body: step["text"])
        step.save
      end
    end

    # すべて保存できたら完了させてshowに飛ばす
    flash[:success] = "レシピを作成しました"
    redirect_to recipe

  end

  # 対象URLが入力したURLに含まれなかったらインポートしない
  def check_url
    input_url = params[:url]
    authorized_url = [
      "delishkitchen.tv/recipes",
      "cookpad.com/recipe",
      "kurashiru.com/recipes",
      "erecipe.woman.excite.co.jp/detail"]

    unless authorized_url.any? { |url| input_url.include?(url) }
      flash.now[:danger] = "このURLはインポートに対応していません"
      render :import
    end
  end

  # ログインしてなかったらログインページにリダイレクト
  def redirect_login
    unless logged_in?
      flash[:dangeer] = "ログインしてください"
      recirect_to login_url
    end
  end


  private

  def recipe_params
    params.require(:recipe).permit(
      :name,
      :description,
      :image,
      :url,
      :recipeYield,
      :cooktime,
      steps_attributes: [
        :id,
        :body,
        :_destroy,
      ],
      ingredients_attributes: [
        :id,
        :name,
        :quantity_amount,
        :_destroy,
      ]
    )
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.slim
- if @recipe.errors.present?
  ul#error_explanation.alert-danger
    - @recipe.errors.full_messages.each do |message|
      li= message

= form_with model: recipe, local: true do |f|

  .recipe_child_section
    h2.recipe_heading レシピ名
    .form-group
      = f.label :name, "レシピ名", class: "sr-only"
      = f.text_field :name, class: "form-control", id: "recipe_name"

  .recipe_child_section
    h2.recipe_heading レシピ概要
    .form-group
      = f.label :description, "レシピ概要", class: "sr-only"
      = f.text_area :description, rows: 2, class: "form-control", id: "recipe_description"

  .recipe_child_section
    h2.recipe_heading レシピ画像
    .form-group
      = f.label :image, "画像", class: "sr-only"
      = f.file_field :image, class: "form-control", id: "recipe_image"

  .recipe_child_section
    h2.recipe_heading 材料
    .ingredients_list.bg-light
      .servings_container.form-inline
        = f.label :recipeYield, "何人分", class: "sr-only"
        = f.text_field :recipeYield, class: "form-control", id: "recipe_recipeYield", placeholder: "何人分"
        span.ml-2 例）2人分
      .list_header.row
        span.col-5.text-center.ingredient_name 材料・調味料
        span.col-5.text-center.ingredient_quantity 分量
      .edit_ingredients_list
        = f.fields_for :ingredients do |ingredient_field|
          = render "ingredient_fields", f: ingredient_field
      .add_field.text-center
        = link_to_add_fields "材料を追加", f, :ingredients

  .recipe_child_section
    h2.recipe_heading 調理時間
    .form-inline
      .form-group
        = f.label :cooktime, "調理時間", class: "sr-only"
        = f.number_field :cooktime, class: "form-control", id: "recipe_cooktime", placeholder: "15"
      span.ml-2 分


  .recipe_child_section
    h2.recipe_heading 作り方
    .edit_steps_list.bg-light
      = f.fields_for :steps do |step_field|
        = render "step_fields", f: step_field
      .add_field.text-center
        = link_to_add_fields "作り方を追加", f, :steps

  = f.hidden_field :id
  = f.hidden_field :user_id, value: current_user.id

  .draft_box
    = f.submit "保存する", class: "btn recipe_create_btn"

app/views/recipes/_ingredient_fields.html.slim
.nested-fields
  .form-row
    .col-5.my-1
      = f.label :name, class: "sr-only"
      = f.text_field :name, class: "form-control", id: "ingredient_name"
    .col-5.my-1
      = f.label :quantity_amount, class: "sr-only" 
      = f.text_field :quantity_amount, class: "form-control", id: "ingredient_quantity"
    = f.hidden_field :_destroy
    .col-auto.my-1.text-right
      = link_to "削除", "#", class: "btn remove_fields"
  

app/views/recipes/_step_fields.html.slim
.nested-fields
  .form-row
    .col-10.my-1
      = f.label :body, class: "sr-only"
      = f.text_area :body, rows: "1", class: "form-control", id: "step_body"
    = f.hidden_field :_destroy
    .col-auto.my-1.text-right
      = link_to "削除", "#", class: "btn remove_fields"
  

app/views/recipes/edit.html.slim
.conteainer
  .row
    .col-md-8.mb-5
      h1 レシピの編集
      .recipe_section
        = render "form", recipe: @recipe

    .col-md-4.mb-5.mt-md-5
      .sidebar-module
        h4 インポートはこちら
        .recipe_create_box.text-center.inner
          = link_to "レシピをインポートする", import_recipes_path, class: "btn recipe_create_btn"

app/views/recipes/import.html.slim
.conteainer
  .row
    .col-md-8.mb-5
      h1 レシピをつくる
      .recipe_section
        .recipe_child_section
          h2.recipe_heading URLを入力
          = form_with url: confirm_recipes_path, class: "import_form", local: true do |f|
            = f.label :url, "URL", class: "sr-only"
            = f.text_field :url, class: "form-control mb-3", placeholder: "https://example.com レシピURLを入力"
            = f.submit "レシピを取り込む", class: "btn recipe_create_btn"

    .col-md-4.mb-5.mt-md-5
      .sidebar-module
        h4 インポート対応サイト
        ul.list-group.list-group-flush
          li.list-group-item 
            |
              cookpad（クックパッド）
            = link_to "https://cookpad.com/", { target: "_blank" } do
              i.fas.fa-external-link-alt
          li.list-group-item 
            |
              DELISH KICHEN（デリッシュキッチン）
            = link_to "https://delishkitchen.tv/", { target: "_blank" } do
              i.fas.fa-external-link-alt
          li.list-group-item
            |
              kurashiru（クラシル）
            = link_to "https://www.kurashiru.com/", { target: "_blank" } do
              i.fas.fa-external-link-alt
          li.list-group-item
            |
              E・レシピ（イーレシピ）
            = link_to "https://erecipe.woman.excite.co.jp/", { target: "_blank" } do
              i.fas.fa-external-link-alt
      .sidebar-module
        h4 いちからつくるはこちら
        .recipe_create_box.text-center.inner
          = link_to "レシピをいちからつくる", "#", class: "btn recipe_create_btn"

app/views/recipes/index.html.slim
.conteainer
  .row
    .col-md-8.mb-5
      h1 レシピ一覧
      - @recipes.each do |recipe|
        .card.flex-row.mb-2.pb2
          .card-img-left.flex-auto
            = link_to recipe_path(recipe) do
              = image_tag recipe.image.variant(resize: "100x100") if recipe.image.attached?
          .card-body.d-flex.flex-column.align-items-start
            h2.recipe_heading
              = link_to recipe.name, recipe_path(recipe)
            .mb-1.text-muted
              = link_to "編集", edit_recipe_path(recipe)
              = " | "
              = link_to "削除", recipe, method: :delete, data: { confirm: "削除してもよいですか？" }
    .col-md-4.mb-5.mt-md-5
      .sidebar-module
        h4 レシピをつくる
        .recipe_create_box.text-center.inner
          = link_to "レシピを一からつくる", new_recipe_path, class: "btn recipe_create_btn"
          = link_to "レシピを取り込む", import_recipes_path, class: "btn recipe_create_btn"
      .sidebar-module
        h4 キーワード
        .keyword_list.inner
      .sidebar-module
        h4 カテゴリ
        .keyword_list.inner
      .sidebar-module
        h4 関連レシピ
        .related_recipes.inner

app/views/recipes/new.html.slim
.conteainer
  .row
    .col-md-8.mb-5
      h1 レシピをつくる
      .recipe_section
        = render "form", recipe: @recipe

    .col-md-4.mb-5.mt-md-5
      .sidebar-module
        h4 インポートはこちら
        .recipe_create_box.text-center.inner
          = link_to "レシピをインポートする", import_recipes_path, class: "btn recipe_create_btn"

app/views/recipes/show.html.slim
.container
  .row
    .col-md-8.mb-5
      h1= @recipe.name
      .recipe_confirm_section
        table.table.table-hover
          tbody
            tr.row
              th.col-2= Recipe.human_attribute_name(:description)
              td.col-10= @recipe.description
            tr.row
              th.col-2= Recipe.human_attribute_name(:image)
              td.col-10= image_tag @recipe.image.variant(resize: "280x280") if @recipe.image.attached?
            tr.row
              th.col-2= Recipe.human_attribute_name(:url)
              td.col-10= link_to @recipe.url, @recipe.url, { target: "_blank" }
            tr.row
              th.col-2= Recipe.human_attribute_name(:recipeYield)
              td.col-10= @recipe.recipeYield
            tr.row
              th.col-2= Recipe.human_attribute_name(:cooktime)
              td.col-10= @recipe.cooktime
            tr.row
              th.col-2= Ingredient.human_attribute_name(:name)
              td.col-10
                p= @recipe.recipeYield
                ul
                  - @recipe.ingredients.each do |ingredient|
                    li
                      = ingredient.name
                      |
                        ： 
                      = ingredient.quantity_amount
            tr.row
              th.col-2= Step.human_attribute_name(:body)
              td.col-10
                ol
                  - @recipe.steps.each do |step|
                    li= step.body

    .col-md-4.mb-5.mt-md-5
      .sidebar-module
        h4 レシピをつくる
        .recipe_create_box.text-center.inner
          = link_to "編集する", edit_recipe_path(@recipe), class: "btn recipe_create_btn"
          = link_to "削除する", @recipe, method: :delete,
                          data: { confirm: "レシピ「#{@recipe.name}」を削除します。よろしいですか？" }, class: "btn recipe_create_btn bg-light"
          = link_to "一覧へ戻る", recipes_path, class: "btn recipe_create_btn"