config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'
  resources :categories
  resources :recipes do
    collection do
      get :import
      post :confirm
    end
  end
  root 'static_pages#home'
  resources :users
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many   :recipes, through: :recipe_category_relations
  has_many   :recipe_category_relations, dependent: :destroy

  validates  :name, presence: true,
                    length: { maximum: 50 },
                    uniqueness: { case_sensitive: true, scope: :user_id } 
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in_user

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
    @categories = Category.all
  end

  def create
    @category = current_user.categories.build(category_params)
    if @category.save
      flash[:success] = "カテゴリを作成しました"
      redirect_to new_category_url
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
    @categories = Category.all
  end

  def update
    @category = Category.find(params[:id])
    
    if @category.update(category_params)
      flash[:success] = "カテゴリを更新しました"
      redirect_to new_category_url
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:success] = "レシピを削除しました"
    redirect_to new_category_url
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.slim
- if @category.errors.present?
  ul#error_explanation.alert-danger
    - @category.errors.full_messages.each do |message|
      li= message
.recipe_child_section
  h2.recipe_heading カテゴリ名を編集
  = form_with model: @category, class: "import_form", local: true do |f|
    = f.label :name, "カテゴリ名", class: "sr-only"
    = f.text_field :name, class: "form-control mb-3", placeholder: "ごはんもの、豚肉、など"
    = f.submit "保存する", class: "btn recipe_create_btn"

app/views/categories/edit.html.slim
.conteainer
  .row
    .col-md-8.mb-5
      h1 カテゴリを編集する
      .recipe_section
        = render "form", category: @category

    .col-md-4.mb-5.mt-md-5
      .sidebar-module
        h4 インポートはこちら
        .recipe_create_box.text-center.inner
          = link_to "レシピをインポートする", import_recipes_path, class: "btn recipe_create_btn"

app/views/categories/index.html.slim
.conteainer
  .row
    .col-md-8.mb-5
      h1 カテゴリ一覧
      .recipe_section
        .recipe_child_section
          h2.recipe_heading URLを入力
          = form_with url: confirm_recipes_path, class: "import_form", local: true do |f|
            = f.label :url, "URL", class: "sr-only"
            = f.text_field :url, class: "form-control mb-3", placeholder: "カテゴリ名を入力"
            = f.submit "カテゴリを作る", class: "btn recipe_create_btn"

    .col-md-4.mb-5.mt-md-5
      .sidebar-module
        h4 インポートはこちら
        .recipe_create_box.text-center.inner
          = link_to "レシピをインポートする", import_recipes_path, class: "btn recipe_create_btn"

app/views/categories/new.html.slim
.conteainer
  .row
    .col-md-8.mb-5
      h1 カテゴリをつくる
      .recipe_section
        = render "form", category: @category

        .recipe_child_section
          h2.recipe_heading カテゴリ一覧
          ul
            - if @categories.present?
              - @categories.each do |category|
                li
                  = category.name
                  = link_to "編集", edit_category_path(category)
                  = link_to "削除", category, method: :delete, data: { confirm: "削除してもよいですか？" }

    .col-md-4.mb-5.mt-md-5
      .sidebar-module
        h4 インポートはこちら
        .recipe_create_box.text-center.inner
          = link_to "レシピをインポートする", import_recipes_path, class: "btn recipe_create_btn"