config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'
  resources :categories
  resources :recipes do
    collection do
      get :import
      post :confirm
    end
  end
  root 'static_pages#home'
  resources :users
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/views/layouts/_header.html.slim
header.navbar.fixed-top.navbar-expand-lg
  .container
    = link_to "cook-note", root_path, id: "logo", class: "navbar-brand"
    button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
      i.fas.fa-bars.text-white.fa-lg.fa-inverse
    nav.collapse.navbar-collapse.justify-content-end#navbarNavDropdown
        ul.navbar-nav.navbar-right.align-items-center
          = form_tag "#", method: "get", class: "form-inline" do
              = text_field_tag :search, "", class: "form-control", placeholder: "レシピをさがす"
              = submit_tag "検索", name: nil, class: "btn search-btn my-md-2"
          li.nav-item
            = link_to "Home", root_path, class: "nav-link"
          - if logged_in?
            li.nav-item
              = link_to "レシピ一覧", root_path, class: "nav-link"
            li.nav-item.dropdown
              = link_to "アカウント", "#", class: "nav-link dropdown-toggle", role: "button", data: { toggle: "dropdown" }, aria: { haspopup: "true", expand: "fale" }
              .dropdown-menu.dropdown-menu-right
                - if current_user.admin?
                  = link_to "ユーザー一覧", "#", class: "dropdown-item"
                = link_to "マイプロフィール", "#", class: "dropdown-item"
                .dropdown-divider
                = link_to "ログアウト", logout_path, method: :delete, class: "dropdown-item"
          - else
            li.nav-item = link_to "ログイン", login_path, class: "nav-link"

app/views/layouts/_message.html.slim
- flash.each do |message_type, message| 
    div.alert class="alert-#{message_type}"
      = message

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cook-Note</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="app-title navbar-expand-md navbar-light bg-light">
      <div class="navbar-brand">cook-note</div>
    <div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Cook-Note
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render "layouts/header"
    = render "layouts/message"
    .container
      = yield
    = debug(params) if Rails.env.development?